### PR TITLE
Fix/aln default parameters

### PR DESCRIPTION
**Pull request by caglorithm**
I removed adaptation as a default parameter and added better comments.

### CODE REVIEW

**Comment by jajcayn** [comment]
will take a look tomorrow

**Comment by caglorithm** [comment]
Oh god so many changes due to black :D sorry about that.

**Comment by jajcayn** [comment]
well, such is life 🤷‍♂

**Comment by jajcayn** [comment]
this PR has a major introduces a lot of formatting changes the same as the other PR #7, right?

**Comment by neurolib-dev** [comment]
Yes, it’s terrible. I didn’t know that VSCode would do a black on ALL files when I save _one_? Or some other mistake might’ve happened...

**Pull request closed without merging**
